### ISSUE TITLE
Missing enhance code in repo.

### ISSUE THREAD

**Issue by mx8435** [llamazing/numnet_plus#8]
Hi, thanks for your open source. Where can we find the enhance code mentioned in your paper? Missing the enhance in `v2` can not reproduce f1 85 in leaderboard ?

**Comment by llamazing** [comment]
We have updated the code to reproduce the `v2` result.
You may reproduce `f1 84-85` with `sh train.sh 345 5e-4 1.5e-5 5e-5 0.01 tag_mspan`.

**Comment by mx8435** [comment]
> `sh train.sh 345 5e-4 1.5e-5 5e-5 0.01 tag_mspan`.

Thanks for your reply. Did you use enhance method to get F1 85 ? 
Besides, can you test whether `gradient accumulation steps` affect the final result ?

**Comment by llamazing** [comment]
#5 has shown that you can reproduce the result with `gradient_accumulation_steps=16`. The `gradient_accumulation_steps=8` may have some unknown effect on reproducing the result(#5, #9).

**Comment by mx8435** [comment]
@llamazing, can you share the train.json and dev.json to help us reproduce result in the leaderboard?
